array_width                   = 60
attr_fn_like_width            = 70
chain_width                   = 60
fn_call_width                 = 60
hard_tabs                     = false
max_width                     = 100
merge_derives                 = true
remove_nested_parens          = true
reorder_imports               = true
reorder_modules               = true
single_line_if_else_max_width = 80
struct_lit_width              = 18
struct_variant_width          = 35
style_edition                 = "2024"
tab_spaces                    = 4
use_field_init_shorthand      = false
use_small_heuristics          = "Default"
use_try_shorthand             = false
