services:
  site:
    container_name: pennsite
    build:
      context: .
      dockerfile: apps/site/Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - pennywise
    depends_on:
      api:
        condition: service_started

  api:
    container_name: pennapi
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - pennywise
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: penndb
    image: postgres:18-trixie
    restart: unless-stopped
    expose:
      - "5432" # Internal only by default
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pennywise
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local

networks:
  pennywise:
    driver: bridge
